### ISSUE TITLE
Option to *not* overwrite existing copies of a movie

### ISSUE THREAD

**Issue by opperpanter** [RuudBurger/CouchPotatoServer#1504]
Hello,

Currently CouchPotato always overwrites an existing movies if it finds a better quality (which is bigger in size).

Sometimes (weekly) the following happens to me:

I have a (rare) movie already downloaded in DVD quality.
CouchPotato finds a HD instance to download.
It downloads it (via Sabnzbd) and the renamer kicks in.
It removes the DVD files and puts the HD files into the movies folder.

The problem is that sometimes CouchPotato downloads the wrong movie.
So in that case I have a HD copy of another movie and my DVD instance has been removed.

Most of the time I can redownload the DVD movie, but that's not ideal.
Especially since you only find out about the wrong movie when you're starting to watch it.

So it would be preferable (for me at least) to keep existing copies and not overwrite them.
Could this be made configurable?

I noticed in the code that the existing copy of the movie has a bigger filesize, it won't get overwritten. It will be renamed so you have both the existing and the new copy.

That would be perfeclty good behaviour for me in all cases, regardless of filesize.

Valentijn

**Comment by leonroy** [comment]
Would love to have this to avoid overwriting my own DVD/Bluray rips.

**Comment by Ashkaan** [comment]
Please make this a priority.  It's awful losing data for a bad download.

**Comment by Ashkaan** [comment]
Does this mean that the feature has been implemented?

I just lost data this week.
