### ISSUE TITLE
PID file bug in init....Run from source on Ubuntu

### ISSUE THREAD

**Issue by KillerKelvUK** [RuudBurger/CouchPotatoServer#2586]
Hi, cloned source yesterday to run in Ubuntu 12.04 and used the init script to start/stop service.  Error message on stop pertained to a missing process id in the PID file...indeed the CP process was still running, only method to stop was a manual kill.

Noted the init script is attempting to chown the PID file location (as in the directory), default specified in the init was /var/run...I don't believe this would be possible unless the CP process was being run as root which you know isn't good.  Simple fix was to create a "couchpotatoe" directory inside /var/run and use the CP /etc/default/couchpotatoe settings file to override the default PID file location...CP_PIDFILE=/var/run/couchpotatoe/.

Guess technically the code is valid and the CP_PIDFILE override is the solution, just looking at this being easier for those with less knowledge to help adoption.

Thanks for the great work.

K

**Comment by RuudBurger** [comment]
The default is already in a folder: https://github.com/RuudBurger/CouchPotatoServer/blob/master/init/ubuntu#L57
You'll also have this issue with any other config I think so keeping it this way.

If you want to provide a pull request that logs the error before it happens, I'll merge it. "pid file not writable" on startup or something.
