### ISSUE TITLE
Renamer does not handle the space character in ") -"

### ISSUE THREAD

**Issue by Piste** [RuudBurger/CouchPotatoServer#2782]
This is a minor bug but all my folders now have a name that I would have to correct... Anyway here is my naming convention: "namethe (year) - quality" yet my movies end up on the destination folder as, let's say: "World's End, The (2013)- 1080P" so I have to go in and add a space manually after the closing parenthesis.
I'll try and identify where this space stripping is happening but for now I wanted to raise this issue.

**Comment by xzKinGzxBuRnzx** [comment]
Using the workaround from #4612 causes file to now start with a space character. Every file renamed while the option 'Clean Name' is disabled results in...

" American Pie Presents The Book of Love (2009) - 1080p.m4v"

my settings for file naming are...

<thename> (<year>) - <quality>.<ext>

The expected output should be...

"American Pie Presents The Book of Love (2009) - 1080p.m4v"

With 'Clean Name' enabled I get these results...

"American Pie Presents The Book of Love (2009)- 1080p.m4v"

So, while 'Clean Name' does fix the ") -" issue it also creates another issue.

**Comment by agipson33** [comment]
Just a thought, would it be possible to replace the current regex of "(\s-)+" with this "(\s-[^\s])+". This additional [^\s] would prevent the matching for instances where " - " is used in the file naming, but wouldn't overlook the instances where something other than a space follows the dash character. Thoughts?

I personally hate having to go back and modify the python code after every upgrade and don't want to disable the replaceDoubles checks.

**Comment by xxJeevesxx** [comment]
@agipson33 Have you tested your suggested regex replacement? I'd really like to try and implement this, even if I have to modify after an update. Do you know which file to manually edit to make the regex change? Thanks in advance!

**Comment by agipson33** [comment]
@xxJeevesxx Yes, I did make the change and it worked flawlessly for me. The file to change is called renamer.py and located within the core/plugins directory. https://github.com/RuudBurger/CouchPotatoServer/blob/master/couchpotato/core/plugins/renamer.py#L903
Replace ('(\s-)+', '-') with ('(\s-[^\s])+', '-'). This change will make the regular expression search for a space character followed by a dash character that is not followed by another space character.

**Comment by xxJeevesxx** [comment]
@agipson33 Great fix, nice work. Works beautifully, thank you for your help!

**Comment by Piste** [comment]
Am I reading correctly from this closure and commit from Ruud that this fix will soon be incorporated in the master and I will benefit from it?

**Comment by RuudBurger** [comment]
Yes

**Comment by agipson33** [comment]
Thank you Ruud!

**Comment by Piste** [comment]
So awesome! Thank you all!!

**Comment by gavsiu** [comment]
I thought this was supposed to be fixed?

Version
    e6fa8b8b9db3c7bdf936f8de66337a86bcaebda5 (10/4/2015, 10:13:08 AM)

<thename> (<year>) - <cd> - <quality>.<ext>

Edge of Tomorrow (2014)- 1080p.en.srt

Or am I doing something wrong?

**Comment by agipson33** [comment]
@gavsiu I just downloaded and installed the latest v3.0.1 windows build and can confirm that the regular expression change is not in the release. I'm not sure what build it will make it into or if it somehow got pulled out by mistake. My steps above for modifying the renamer.py script on line 903 are still valid.

**Comment by xxJeevesxx** [comment]
Thanks for the update! 


Martin

**Comment by agipson33** [comment]
It looks like the change is in the master and develop branches, but hasn't made it into the desktop branch yet. I'm not 100% sure which branch the windows download is built from, but I assume it would be the Desktop one.

@RuudBurger Is this something you can help out with very easily?

**Comment by gavsiu** [comment]
My install is on FreeNAS and I am using Master branch.

Updater    source, master

Unless the fix has been applied since I last posted.
