### ISSUE TITLE
[webui] direct call with username/password or apikey

### ISSUE THREAD

**Issue by farfromrefug** [RuudBurger/CouchPotatoServer#2939]
In my app i want to have a webview showing CP settings page (the idea is that i don't want to redo the whole settings page for now).

I can already point to that page using "/settings" but then the user will be asked to login first.
Is there already any way to bypass the login? (i know username/password/apikey)?
If not do you think it would be possible to add html parameters for username/password/apikey?

Thanks

EDIT: i have tried with the "Authorization" header field without success

**Comment by RuudBurger** [comment]
you can post the user + password to the login page.
