### ISSUE TITLE
Restarting CPS on FreeBSD from webpage does not update pidfile

### ISSUE THREAD

**Issue by dellipse** [RuudBurger/CouchPotatoServer#3306]
When restarting the CouchPotatoServer from within the web interface, the pidfile does not get updated, so service scripts and monitoring software cannot properly perform actions that depend on it.

**Comment by thejrose1984** [comment]
Not sure if this is related, but I cannot start or restart using the current init script for FreeBSD (I am using CPS within a FreeNAS jail). Here is the output I get:
`Starting couchpotato.`
`env: python: No such file or directory`
`/etc/rc.d/couchpotato: WARNING: failed to start couchpotato`
