### ISSUE TITLE
Unable to process VIDEO_TS movies

### ISSUE THREAD

**Issue by h3llrais3r** [RuudBurger/CouchPotatoServer#3609]
### Steps to reproduce:
1. Download a DVD release (VIDEO_TS folder) manually (not by searching in Couchpotato)
2. Copy it into the Couchpotato watch dir
3. Couchpotato tries to process it, but doesn't seem to find the title

### Information:
Movie(s) I have this with: all movies of the type DVD (VIDEO_TS)
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 45b2dff6 (2014-06-29 11:01:09)
Running on: Windows 8

### Logs:
```
07-11 10:47:54 ERROR [ato.core.helpers.variable] Could not get title for library item: {'files': {'subtitle_extra': [], 'subtitle': [], 'nfo': [], 'movie': ['M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_2.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VIDEO_TS.BUP', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_02_0.BUP', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VIDEO_TS.IFO', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_02_0.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_4.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_0.IFO', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VIDEO_TS.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_0.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_1.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_02_0.IFO', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_3.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_02_1.VOB', 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS\\VTS_01_0.BUP'], 'leftover': [], 'movie_extra': [], 'trailer': []}, 'media': {}, 'release_download': None, 'identifiers': [u'1989 dvdr', u'1989'], 'is_dvd': True, 'meta_data': {'audio_channels': 2.0, 'resolution_width': 0, 'video': '', 'aspect': 1, 'quality': {'tags': ['pal', 'ntsc', 'video_ts', 'audio_ts', ('dvd', 'r'), 'dvd9'], '_rev': '0002017a', 'size_min': 3000, 'is_3d': False, 'alternative': ['br2dvd', ('dvd', 'r')], 'size': (3000, 10000), 'identifier': 'dvdr', '_t': 'quality', 'size_max': 10000, 'label': 'DVD-R', 'ext': ['iso', 'img', 'vob'], 'allow': [], '_id': '86f875959b8e4df48fb60f09d372e526', 'order': 4}, 'size': 4205L, 'quality_type': 'SD', 'group': '', 'resolution_height': 0, 'source': None, 'audio': ''}, 'parentdir': 'M:\\Downloads\\complete\\couchpotato\\All Dogs Go to Heaven (1989)\\VIDEO_TS', 'dirname': 'All Dogs Go to Heaven (1989)', 'subtitle_language': {}} 
```

For some kind of reason, Couchpotato does not want to process VIDEO_TS folders

**Comment by h3llrais3r** [comment]
Any progress on this issue?
Non of my DVD's (VIDEO_TS) are listed anymore in couchpotato...:(

**Comment by rhodespa** [comment]
It seems to be in createStringIdentifier in scanner.py. This doesn't seem to correctly create an identifier for DVD files. I have a file path of "I:\testing\40 Days And 40 Nights (2002)\VIDEO_TS\VIDEO_TS.BUP" going in creating an identifier of 2002. Setting it to path_split[-2] seems to be wrong.

**Comment by h3llrais3r** [comment]
No solution yet?

**Comment by rhodespa** [comment]
apologies - i haven't quite figured out how to use github yet. In scanner.py, in createStringIdentifier around line 803, move the section

    if exclude_filename:
            identifier = identifier[:len(identifier) - len(os.path.split(identifier)[-1])]

to BEFORE the try block:

        try:
            path_split = splitString(identifier, os.path.sep)
            identifier = path_split[-2] if len(path_split) > 1 and len(path_split[-2]) > len(path_split[-1]) else path_split[-1] # Only get filename
        except: pass

That fixes the problem for me. When I have more time, i will figure out how to submit.

**Comment by h3llrais3r** [comment]
@rhodespa Thanks for explanation. :+1: 
Meanwhile I created a PR for this myself. ;)

**Comment by h3llrais3r** [comment]
Since it's merged into master, and everything works again, I'll close it.

**Comment by rhodespa** [comment]
Good stuff!
