### ISSUE TITLE
3D Quality pulling from YIFY Torrent

### ISSUE THREAD

**Issue by quedini** [RuudBurger/CouchPotatoServer#3745]
There seems to be an issue when trying to snatch 3D movies from YIFY Torrents.  It finds it then ignores it as being Wrong. In the short term I have just backed up my old db and delete it and added a quality profile for 3D in the main.py.  I know that the addition of 3D handling was supposed to aleviate that. I figured i would report it in case anyone else has had this issue or has the solution that i missed. 

For my setup. I am using the 3D HD quality, with Br-Rip moved to the top with 3D and Finished checked.
I also have a category for 3D, that prefers the word 3D being in the title. When requiring 3D i didn't get any return results either. 

Below I have the json string returned showing the 3D file returned. and the snipped from the debug log.

Here's the link CP used to get the json. You will notice 3D is the first item returned
http://yify.unlocktorrent.com/api/list.json?keywords=tt2369135&quality=brrip

And here's the info from the debug log.
http://pastebin.com/yXVedb6U

**Comment by RuudBurger** [comment]
Tested and works
