### ISSUE TITLE
Couchpotato not longer sending movies to sabnzbd

### ISSUE THREAD

**Issue by RoRoo1977** [RuudBurger/CouchPotatoServer#3776]
### Information:
Movie(s) I have this with: all movies in my list with both nzb providers (dognzb and nzbs.org)
Quality of the movie being searched: HD 720P and 1080P
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) e75a8529 (2014-07-17 22:24:48)
Running on: Linux

### Logs:
```
08-10 15:31:05 ERROR [tato.core.plugins.release] Tried to download, but the "nzb" provider gave an error: Traceback (most recent call last):
  File "/apps/CouchPotato/couchpotato/core/plugins/release/main.py", line 294, in download
    filedata = data.get('download')(url = data.get('url'), nzb_id = data.get('id'))
  File "/apps/CouchPotato/couchpotato/core/media/_base/providers/nzb/newznab.py", line 190, in download
    if e.code == 503:
AttributeError: 'HTTPError' object has no attribute 'code' 
```

**Comment by RuudBurger** [comment]
This code doesn't exist anymore. Please make sure you're running the latest version

**Comment by RoRoo1977** [comment]
It was the latest version on 10 Aug 2014 ;)
