### ISSUE TITLE
CPserver won't start (IOError("Storage doesn't exists!"))

### ISSUE THREAD

**Issue by bootloos** [RuudBurger/CouchPotatoServer#4400]
hello,
After a dirty shutdown, I'm not being able to start cp again.
It is running under debian wheezy and I'm starting it with "service couchpotato start" it does start but less than a minute later it stops. I've tried starting it without daemonizing it and this is what I get:

`[shell]# /usr/bin/python CouchPotato.py  --pid_file=/var/couchpotato/couchpotato.pid --data_dir=/var/couchpotato --config_file=/var/couchpotato/couchpotato.ini
Traceback (most recent call last):
  File "CouchPotato.py", line 133, in <module>
    l.run()
  File "CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/usr/local/CouchPotatoServer/couchpotato/runner.py", line 140, in runCouchPotato
    db.open()
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 43, in _inner
    res = f(*args, **kwargs)
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/database_super_thread_safe.py", line 93, in open
    res = super(SuperThreadSafeDatabase, self).open(*args, **kwargs)
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/database.py", line 571, in open
    index.open_index()
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/hash_index.py", line 112, in open_index
    self._open_storage()
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/hash_index.py", line 137, in _open_storage
    self.storage.open()
  File "/usr/local/CouchPotatoServer/libs/CodernityDB/storage.py", line 99, in open
    raise IOError("Storage doesn't exists!")
IOError: Storage doesn't exists!`

I've checked the file /usr/local/CouchPotatoServer/libs/CodernityDB/storage.py and it does exist and have the correct permissions (i've even tried to give it a 777 just in case)

I've been also having a look to issue #3831 but I can't even start CP to look for the folder you talk about. 

I guess this a corruption problem but I don't know how to fix it and I don't want to lose my database either, What can I do?

**Comment by RuudBurger** [comment]
Please check the /var/couchpotato folder. There is a database folder in there.
You can shutdown CP and you can remove everything accept _indexes/00id.py and id_store, id_buck.
Then start CP again and it should rebuild your database.

There's also a db_backup folder in /var/couchpotato, which you can use to restore stuff.

**Comment by ninovanhooff** [comment]
What worked for me is deleting the complete database folder (create a copy just to be sure)

**Comment by drewcovi** [comment]
@RuudBurger heroic. thanks for this little tip to rebuild the database... any chance we can get this operation *automated*? Although @ninovanhooff deleted the entire directory, that basically starts you from square one. 

I was also a bit too lazy to remove all but the one file in _indexes. then finally followed your instructions "to the t"  and I'm back!

**Comment by pettazz** [comment]
What happens if I don't have a /var/couchpotato folder at all?
