### ISSUE TITLE
Extension, show proper error response on movie after "loading movie info"

### ISSUE THREAD

**Issue by zobi** [RuudBurger/CouchPotatoServer#4413]
Hello, i'm french and i use www.allocine.fr to find my movie.
With safari extension (but same problem on chrome) when i'm on a movie page like : 
http://www.allocine.fr/film/fichefilm_gen_cfilm=222512.html
I click on my extension and it say : "loading movie info" ...
but nothing appears ... 
(It works very well on imdb)

Thanks a lot

**Comment by RuudBurger** [comment]
Yeah there really needs to be better error handling for the extension.

**Comment by RuudBurger** [comment]
Don't know if I can use the release year (that is on the page) though, as that would cause other movies to have the same kind of issue.

**Comment by Namlaz** [comment]
Also, it can be more complicated than that, as there are many Releases dates depending on the country.
I *suppose* themoviedb/imdb take the first release date as a reference, but that doesn't change the fact that as for this example, the French website shows its release date that can be 1 year before/after the first one...

The solution can always be a **Recommended websites** type of thing but that's not very open sadly.

**Comment by RuudBurger** [comment]
Updated the extension to give feedback on failed movie info

**Comment by Namlaz** [comment]
Thanks, just waiting for it to update in the Firefox addon database :)
