### ISSUE TITLE
It cannot manage Unicode characters in directory names.

### ISSUE THREAD

**Issue by ovidiub13** [RuudBurger/CouchPotatoServer#4439]
### Steps to reproduce:
1. Rename a directory to "Descărcări"
2. Use it as a source directory for the renamer

### Information:
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 2f5526d5 (2015-01-02 19:54:36)
Running on: OpenMediaVault (linux, debian)

### Logs:
```
01-03 01:02:39 ERROR [otato.core.plugins.manage] Failed updating library: Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/plugins/manage.py", line 117, in updateLibrary
    if not os.path.isdir(folder):
  File "/usr/lib/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0103' in position 19: ordinal not in range(128) 
```

**Comment by redglory** [comment]
Your OS is encoding unicode to ascii before os.stat is evaluating path as a folder. Perhaps you don't have your locale set to UTF-8 ?! see http://perlgeek.de/en/article/set-up-a-clean-utf8-environment

**Comment by ovidiub13** [comment]
@redglory I've followed that tutorial you've sent me, and set (again) everything to UTF-8. CouchPotato still does not see directories containing the "ă" character. (and probably others)

**Comment by ovidiub13** [comment]
![imagine12](https://cloud.githubusercontent.com/assets/3527534/5602117/b9bb23da-9340-11e4-9112-29304a818295.png)

The Downloads dir is a symlink to the Descărcări dir. Temporary workaround.

**Comment by RuudBurger** [comment]
I think this should fix it: http://stackoverflow.com/questions/2276200/changing-default-encoding-of-python
