### ISSUE TITLE
Question about display movie name: the movie or movie, the

### ISSUE THREAD

**Issue by EvtK** [RuudBurger/CouchPotatoServer#4477]
It seems to me that movies (in all views), were sorted like 'the movie' before an now are sorted like 'movie, the'. Or is this some kind of setting I have accidentally changed.. Can't find it though. 😀

To make sure, I would like to have them sorted as 'the movie'

Thanks

**Comment by zone31** [comment]
i would also like the format to be <the movie>, maybe a toggle between them in settings?

**Comment by RuudBurger** [comment]
It has always been `movie, the` by default. You cant' change this in the interface.
You can however change the renamer options to name the folder like `the movie`. You'll get a lot of movies starting with a `t` though ;)
