### ISSUE TITLE
CP Dealing With Special Characters Badly on Synology

### ISSUE THREAD

**Issue by nicktones** [RuudBurger/CouchPotatoServer#4521]
CP isn't dealing very well with special characters on Synology NAS.  If there is a movie with a special character - that character gets substituted even with it can actually be used in a file name.  For example:

National Lampoon's European Vacation (1985)

is renamed too:

National Lampoonâs European Vacation (1985)

This is not needed as ' is an ok character in files names.  Same happens for other language characters.  For example:

Les Misérables (1998)

is renamed to:

Les MisĂŠrables (1998) 

Again é is an acceptable character.  This not dealing with these characters properly causes problems with the titles being recognised later on down the line with Kodi for example.  Also CP has issues moving the folders once they have been renamed like this.

Please let me know if more info is required here

**Comment by f3bruary22** [comment]
This is, I believe, an encoding issue on Synology. I don't have this issue cause I made sure the shell environment uses UTF8.

Try putting this in your /etc/profile

export LC_ALL=en_US.utf8
export LANG=en_US.utf8

Restart, and try to reproduce the error.

**Comment by nicktones** [comment]
Just checked and those lines already exist in that file.

**Comment by f3bruary22** [comment]
what's the output of the 'locale' command ?

**Comment by nicktones** [comment]
TARDIS> LANG=en_US.utf8
TARDIS> LC_CTYPE="en_US.utf8"
TARDIS> LC_NUMERIC="en_US.utf8"
TARDIS> LC_TIME="en_US.utf8"
TARDIS> LC_COLLATE="en_US.utf8"
TARDIS> LC_MONETARY="en_US.utf8"
TARDIS> LC_MESSAGES="en_US.utf8"
TARDIS> LC_PAPER="en_US.utf8"
TARDIS> LC_NAME="en_US.utf8"
TARDIS> LC_ADDRESS="en_US.utf8"
TARDIS> LC_TELEPHONE="en_US.utf8"
TARDIS> LC_MEASUREMENT="en_US.utf8"
TARDIS> LC_IDENTIFICATION="en_US.utf8"
TARDIS> LC_ALL=en_US.utf8

**Comment by nicktones** [comment]
Do I need to be doing that with a particular user or are these settings system wide?

**Comment by f3bruary22** [comment]
I'm not sure about that actually. You could try issueing that command as the user CP is running as. Another thing I wanted to ask: Do you use an ssh client to log in ? Putty ? Make sure the ssh client also has the correct encoding applied.

**Comment by RuudBurger** [comment]
This issue is already reported
