### ISSUE TITLE
WALL·E not being picked up by CP Manager

### ISSUE THREAD

**Issue by eangulus** [RuudBurger/CouchPotatoServer#4584]
As the title states. Have the movie folder and files name as such WALL·E (2008).

Also same thing happens with the movie Æon Flux

**Comment by clinton-hall** [comment]
non utf-8 characters in the file name?

**Comment by RuudBurger** [comment]
I need some more logging

**Comment by eangulus** [comment]
Can you tell me where the actual log file should be?
Been trying to find the log file so I can scan thru it for the relevant parts. There is over 800 Movies and its very difficult to try to find the problem parts via the UI.

**Comment by skarekrow** [comment]
It would be wherever you have the data directory set. He cannot tell you that unfortunately.

**Comment by eangulus** [comment]
After many attempts to find something in the logs, I have failed.
Couchpotato doesn't even attempt to find either movie.

I did find something interesting thou if I go to the Manage section in Settings, and then navigate the folder selection, Æon Flux and WALL·E do not even show up the drop down. So it seems that couchpotato is not just not reading them, it doesn't even know they exist, even thou they do.

**Comment by RuudBurger** [comment]
You can see the logs under the cog-menu. Or via Settings > About to find the paths where data is stored.
You can change your manage folder to a test folder containing only the problematic movies. 

If you post logs, do it via the log interface and make sure to fill in all the ... (dots)

**Comment by eangulus** [comment]
I did find the logs, and did a search on the log file. BOth the mentioned movies are not even scanned at all. They are in folders name exactly as the names in the first post, and are in the same folders as the rest of the movies.

I think it has something to do with how Couchpotato is reading the directories as when browsing the folders in manage settings they don't show up.

**Comment by RuudBurger** [comment]
Don't think. Just provide what is asked for (3 times now)

**Comment by eangulus** [comment]
If there is nothing related to the problem in the logs, then what do you want me to do?
Can't get blood from a stone...

**Comment by RuudBurger** [comment]
Like I said: 
``` You can change your manage folder to a test folder containing only the problematic movies.

If you post logs, do it via the log interface and make sure to fill in all the ... (dots)```

**Comment by eangulus** [comment]
Just did as I was asked.

https://github.com/RuudBurger/CouchPotatoServer/issues/4611

**Comment by RuudBurger** [comment]
Whatever...
