### ISSUE TITLE
 "Loading 'Snatched & Available'" request hanging forever

### ISSUE THREAD

**Issue by cpoissonnier** [RuudBurger/CouchPotatoServer#4588]
### Steps to reproduce:
1. Login
2. Go to home page, and wait forever

### Information:
Providers I use: As you asked me last time, Torrentbytes is disabled, but I use other torrents searchers (torrentz, torrentday & kickasstorrent)
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer develop) 770c2be1 (2015-01-17 13:04:47)
Running on: Windows, with directory/movie names with french characters (such as "à" or "é") pretty much everywhere

### Logs:
```
01-27 20:21:27 ERROR [          couchpotato.api] Failed proper encode: Traceback (most recent call last):
  File "C:\Users\Clement\AppData\Roaming\CouchPotatoServer\couchpotato\api.py", line 147, in sendData
    self.finish(result)
  File "C:\Users\Clement\AppData\Roaming\CouchPotatoServer\libs\tornado\web.py", line 867, in finish
    self.write(chunk)
  File "C:\Users\Clement\AppData\Roaming\CouchPotatoServer\libs\tornado\web.py", line 656, in write
    chunk = escape.json_encode(chunk)
  File "C:\Users\Clement\AppData\Roaming\CouchPotatoServer\libs\tornado\escape.py", line 88, in json_encode
    return json.dumps(value).replace("</", "<\\/")
  File "C:\Python27\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 74: invalid start byte 
```

I wish I knewPython so I could help you. Thanks again for your amazing work !

**Comment by RuudBurger** [comment]
Please use search first. Already fixed in dev

**Comment by cpoissonnier** [comment]
I'm already on dev branch and up-to-date :/

**Comment by cpoissonnier** [comment]
FYI, I had to backup the movies I wanted to download thanks to CP-BackupTool(https://github.com/clinton-hall/CP-BackupTool), removed all data of Couch Potato, restored my settings, added my wanted movies and it's working now.

**Comment by RuudBurger** [comment]
Could you do another search with torrentbyte enabled. And search for gone girl. That was the one causing the issue before. 
If you still have the issue, please send me a copy of your database. Info (at) couchpota.to

**Comment by cpoissonnier** [comment]
I done what you asked me, and it looks like everything works now.
Thanks !
