### ISSUE TITLE
Cant manage it to work...

### ISSUE THREAD

**Issue by Jikz** [RuudBurger/CouchPotatoServer#4662]
### Steps to reproduce:
1. When I simply want to download anything with CouchPotato
2. ..

### Information:
Movie(s) I have this with: Thor, Thor: The Dark World, Guardians of the Galaxy
Quality of the movie being searched: 1080p
Providers I use: nzbplanet.net, nzbid.org
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 5b1dd686 (2015-01-17 13:04:58)
Running on: DSM 5.0-4493

I´m deeply sorry if I posting anything wrong, and beg admins to not delete this post and hopefully someone can help me....

### Logs:
```
02-15 04:51:05 ERROR [tato.core.plugins.release] Tried to download, but the "nzb" provider gave an error: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/plugins/release/main.py", line 311, in download
    filedata = data.get('download')(url = data.get('url'), nzb_id = data.get('id'))
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/nzb/newznab.py", line 196, in download
    response = e.read().lower()
AttributeError: 'HTTPError' object has no attribute 'read' 
```

**Comment by RuudBurger** [comment]
Anything above this?
