### ISSUE TITLE
Error Handling Directory Names with Special Characters

### ISSUE THREAD

**Issue by prodigalpogue** [RuudBurger/CouchPotatoServer#4669]
### Steps to reproduce:
Upon upgrading to v2.6.2, the application fails to access a directory containing a special character (a unicode bullet or •) in its name.  Error has been seen with regard to "To:" and "From:" renamer targets.  Removing the special character returns functionality.  Downgrading to 2.6.1 also eliminates the issue.

### Information:
OS: Mac OS X 10.10.2
CP: CouchPotato 2.6.2

### Sample Logs:
```
02-15 19:35:56ERROR[tato.core.plugins.scanner] Folder doesn't exists: /Volumes/SUPPLYâ€¢R/Downloads/Completed/Movies

02-15 22:04:11ERROR[tato.core.plugins.renamer] Both the "To" and "From" folder have to exist.
```

This is my first issue report - apologies if I missed something.  Thanks!

**Comment by RuudBurger** [comment]
Thanks, this is fixed in develop.
I'll make a new build soonish. For whatever reason if you add 2 or more of those dots, it works fine... so you can do that while you wait ;)
