### ISSUE TITLE
Not picking up 720p movie

### ISSUE THREAD

**Issue by johnmerrick1972** [RuudBurger/CouchPotatoServer#4683]
http://pastebin.com/UuDAqUwv
http://i.imgur.com/8lCuAj2.jpg

https://couchpota.to/forum/viewtopic.php?f=3&t=1445&start=20

**Comment by RuudBurger** [comment]
It's a brrip. Which is correct

**Comment by johnmerrick1972** [comment]
Any idea why it's not snatching the movie at all? Is it in my quality settings? 
Clinton on the support forum asked me to submit the issue.

**Comment by clinton-hall** [comment]
I believe the issue was that this was identified as brrip when searching 720p, but it never got found when searching for BRRip. So the search categories need tweaking for that provider?

**Comment by johnmerrick1972** [comment]
It's available from various providers and it's a web-dl which cp views as a brrip. Thats fine.
But i have brrip specified as a quality in my profile so why isn't it snatching it if it matches that?
