### ISSUE TITLE
Renamer never runs

### ISSUE THREAD

**Issue by quinnvanorder** [RuudBurger/CouchPotatoServer#4782]
I am running CP in a virtual environment on a whatbox seedbox.
Here are my debug logs
http://pastebin.com/raw.php?i=SKscrEZc

I am running version abfd9d08 (‎3‎/‎23‎/‎2015‎ ‎8‎:‎23‎:‎09‎ ‎AM)

Essentially renamer will never run. In the logs you will never see it. This is a fresh installation of CP on this slot. I am using the same configuration that I have used on another slot.

I have tried manually running it by browsing to 

http://serveraddress.whatbox.ca:myport/api/MyApiKeyHereObviously/renamer.scan

it shows success in my browser, and the logs show nothing. 

Thus far it has successfully snatched, and downloaded the file in question. From there, rtorrent has rules to move the completed download to my *./extracted folder. Renamer never logs as even looking for movies, it never logs when I try to manually run it (correct me if I am wrong, but I can just paste that api link above into a browser to run it right? I have never used api keys before).

Thank you for your help.

**Comment by RuudBurger** [comment]
Enabled debug logs. And maybe point it to another folder for testing.
the apicall should give the correct results in logs.

Maybe try with a fresh config, just for testing. I see you changed the cronjob timers
