### ISSUE TITLE
Notification Pushbullet status:available

### ISSUE THREAD

**Issue by kesurof** [RuudBurger/CouchPotatoServer#4813]
![2015-04-02_14h13_571](https://cloud.githubusercontent.com/assets/11770905/6963988/2531e03c-d945-11e4-9ee1-dd2e542fa2da.png)

Hello,
I will wish to activate a Pushbullet notification when a film is found not only at the time the movie is downloaded.
To be accused of the time he must selected the best source. Thank you very much for your work.

Bonjour, 
je souhaiterai pouvoir activer une notification Pushbullet, au moment ou un film est trouvé et pas seulement au moment ou le film est téléchargé.
Afin d'être prevenu du moment ou il faut séléctionné la meilleur source. Merci beaucoup pour votre travail.

**Comment by RuudBurger** [comment]
This already is on by default.
When a search is trigger before ETA you'll get a message.

If you have disabled auto snatching, then no there isn't a message for every movie. And this isn't how CP is supposed to be used ;)
