### ISSUE TITLE
Couchpotato has added 60 movies to wanted list overnight

### ISSUE THREAD

**Issue by brendann993** [RuudBurger/CouchPotatoServer#4824]
### Steps to reproduce:
1. None, Has appeared randomly, has occurred once before but CouchPotato has been re-installed since.
there is approx 60 movies 55 of them I have definitely not added my self. I don't think the log goes back far enough to the add point. Will add more logs once has occurred again

### Information:
Movie(s) I have this with: About Elly; Addicted; Alexander and the Terrible, Horrible, No Good, Very Bad Day; American Sniper; Annie; Best of Me, The; Big Hero 6; Birdman; Black Souls; Cinderella  + Many others
Quality of the movie being searched: 720P, 1080P, BR-Rip, DVD-Rip
Providers I use: Kickass, Torrentz, Thepiratebay, Yify
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) abfd9d08 (2015-03-23 23:23:09)
Running on: Synology DSM 5.1

http://pastebin.com/wdDTsEK8

### Logs:
```
04-06 21:37:23  INFO [edia._base.providers.base] Found: score(831) on KickAssTorrents: Starred Up 2014 720P BRRiP XVID AC3-MAJESTIC 
04-06 21:37:23  INFO [edia._base.providers.base] Found: score(146) on ThePirateBay: Rosewater (2014) 1080p BluRay DTS x264 -BY @Kamalesh 
04-06 21:37:23  INFO [hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/torrent/11556611/Predestination_2014_720p_BRRIP_H264_AAC-MAJESTiC, data: [] 
04-06 21:37:23  INFO [hpotato.core.plugins.base] Opening url: get https://kickass.to/m-i1911658/, data: [] 
04-06 21:37:23  INFO [hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22penguins+of+madagascar+2014%22%20size%204000m%20-%2020000m%20seed%20%3E%200, data: [] 
04-06 21:37:23  INFO [hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/search/%22Penguins+of+Madagascar+2014%22/0/7/207, data: [] 
04-06 21:37:24  INFO [edia._base.providers.base] Found: score(19318) on KickAssTorrents: Interstellar 2014 1080p BluRay x264 DTS-RARBG 
04-06 21:37:24  INFO [edia._base.providers.base] Found: score(6517) on KickAssTorrents: Ouija 2014 HC HDRip XViD AC3-juggs[ETRG] 
04-06 21:37:24  INFO [edia._base.providers.base] Found: score(1785) on ThePirateBay: Home Sweet Hell 2015 HDRip XviD AC3-EVO 
04-06 21:37:24  INFO [hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/torrent/11680406/Nightcrawler_(2014)_720p_5.1ch_BRRip_AAC_x264_-_[GeekRG], data: [] 
04-06 21:37:24  INFO [hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/search/%22Big+Hero+6+2014%22/1/7/207, data: [] 
04-06 21:37:24  INFO [edia._base.providers.base] Found: score(430) on KickAssTorrents: Rosewater 2014 BRRip XviD AC3-EVO 
04-06 21:37:24  INFO [hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22human+capital+2013%22%20size%203000m%20-%2010000m%20seed%20%3E%200, data: ```
http://pastebin.com/wdDTsEK8 for more log

**Comment by brendann993** [comment]
I have cleared my wanted list & Logs(I have backup if needed) I have also enable debug logs. I have no automation turned on and I never have.

**Comment by brendann993** [comment]
So its happened twice since. First time again I missed the logs. This time I have managed to grab them in time.  Bellow is a snippet of the logs with debugging on. When one of the movies was randomly added. Again I have all automation turned off & it always has been.

'''04-20 21:23:30 DEBUG [36m[hpotato.core.plugins.base] Getting cache suggestion_cached[0m
04-20 22:24:00 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
04-20 22:24:00 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
04-20 22:24:10 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
04-20 22:24:10 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m
04-20 22:24:25 DEBUG [36m[o.core.notifications.core] Cleaning messages[0m
04-20 22:24:25 DEBUG [36m[o.core.notifications.core] Done cleaning messages[0m
04-20 22:25:52 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt2800038/?adding=1, data: [][0m
04-20 22:25:54 DEBUG [36m[hpotato.core.plugins.base] Setting cache 21d6c68ed8f136ada902ec32ae5fee2a[0m
04-20 22:25:54 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt2800038/, data: [][0m
04-20 22:25:54 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2800038, data: [][0m
04-20 22:25:54 INFO [0m[hpotato.core.plugins.base] Opening url: get http://api.themoviedb.org/3/movie/tt2800038?api_key=xxx&append_to_response=alternative_titles, data: [][0m
04-20 22:25:54 DEBUG [36m[hpotato.core.plugins.base] Setting cache ac23535814daaeece5df4f52f7605bf7[0m
04-20 22:25:55 DEBUG [36m[hpotato.core.plugins.base] Setting cache c3462e28c70d7f1ba9baf5912d282c25[0m
04-20 22:25:57 ERROR [31m[hpotato.core.plugins.base] Failed opening url in OMDBAPI: http://www.omdbapi.com/?type=movie&i=tt2800038 Traceback (most recent call last):
ConnectTimeout: HTTPConnectionPool(host='www.omdbapi.com', port=80): Max retries exceeded with url: /?type=movie&i=tt2800038 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fcc94430390>, 'Connection to www.omdbapi.com timed out. (connect timeout=3)'))
[0m
04-20 22:25:57 DEBUG [36m[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last):
ConnectTimeout: HTTPConnectionPool(host='www.omdbapi.com', port=80): Max retries exceeded with url: /?type=movie&i=tt2800038 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fcc94430390>, 'Connection to www.omdbapi.com timed out. (connect timeout=3)'))
[0m
04-20 22:25:57 DEBUG [36m[   couchpotato.core.event] Return modified results for movie.info[0m
04-20 22:25:58 DEBUG [36m[hpotato.core.plugins.base] Acquiring lock: media.get.196a6c0e69b547dd8a26e9eae71988a1[0m
04-20 22:25:58 DEBUG [36m[hpotato.core.plugins.base] Getting cache ac23535814daaeece5df4f52f7605bf7[0m
04-20 22:25:58 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt2800038, data: [][0m
04-20 22:25:58 DEBUG [36m[hpotato.core.plugins.base] Getting cache c3462e28c70d7f1ba9baf5912d282c25[0m
04-20 22:25:58 DEBUG [36m[o.core.notifications.core] Notifying frontend[0m
04-20 22:25:58 DEBUG [36m[o.core.notifications.core] Done notifying frontend[0m
04-20 22:25:58 DEBUG [36m[hpotato.core.plugins.base] Getting cache suggestion_cached[0m
04-20 22:25:58 DEBUG [36m[hpotato.core.plugins.base] Setting cache suggestion_cached[0m
'''

**Comment by RuudBurger** [comment]
I don't see any automation starting the searches.
Can you do a search in all the logs?
