### ISSUE TITLE
CP stopped working...

### ISSUE THREAD

**Issue by Grimjack69** [RuudBurger/CouchPotatoServer#4829]
Since some days CP stopped download torrents. According to logs it seems lika it dosen´t evet tries unless I manually pick a release. When doing so I got these errors in log.

### Steps to reproduce:
1. Search for Fifty shades of grey (easy target)
2. Manual download best release found

### Information:
Movie(s) I have this with: all
Quality of the movie being searched: ...
Providers I use: 
Version of CouchPotato: desktop: 2.6.3
Running on: win7 64

### Logs:
```
04-09 10:12:14INFO[edia._base.providers.base] Found: score(810) on ThePirateBay: Fifty.Shades.of.Grey.2015.HD720p.XviD-VAiN
04-09 10:12:14INFO[hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/torrent/11793520/Fifty.Shades.of.Grey.2015.HD720p.XviD-VAiN, data: []
04-09 10:12:16INFO[edia._base.providers.base] Found: score(1029) on ThePirateBay: Fifty.Shades.of.Grey.2015.HD720p.XviD-VAiN
04-09 10:12:16INFO[hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/torrent/11726796/Fifty_Shades_of_Grey_[2015]_HD720p_XviD-VAiN, data: []
04-09 10:12:19INFO[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/validate/ZmlmdHkgc2hhZGVzIG9mIGdyZXkgWzIwMTVdIGhkNzIwcCB4dmlkLXZhaW4=/, data: []
04-09 10:12:19INFO[edia._base.providers.base] Found: score(477) on ThePirateBay: Fifty Shades of Grey [2015] HD720p XviD-VAiN
04-09 10:12:19INFO[hpotato.core.plugins.base] Opening url: get https://dieroschtibay.org/search/%22Fifty+Shades+of+Grey+2015%22/1/7/201, data: []
04-09 10:12:20INFO[core.media.movie.searcher] Found 86 releases for "Fifty Shades of Grey" before ETA. Select and download via the dashboard.
04-09 10:13:44INFO[hpotato.core.plugins.base] Opening url: post https://api.couchpota.to/suggest/, data: ['ignore', 'movies']
04-09 10:13:44INFO[iders.info.couchpotatoapi] Found suggestions for 697 movies, 0 ignored
04-09 10:13:54INFO[hpotato.core.plugins.base] Opening url: get https://torcache.net/torrent/BFF9E2F76C55DA6CFEC07ACD6961BE5607E09B6B.torrent, data: []
04-09 10:14:13INFO[hpotato.core.plugins.base] Opening url: get http://torrage.com/torrent/BFF9E2F76C55DA6CFEC07ACD6961BE5607E09B6B.torrent, data: []
04-09 10:14:34INFO[hpotato.core.plugins.base] Opening url: get https://zoink.it/torrent/BFF9E2F76C55DA6CFEC07ACD6961BE5607E09B6B.torrent, data: []
04-09 10:14:41ERROR[ato.core._base.downloader] Failed converting magnet url to torrent: BFF9E2F76C55DA6CFEC07ACD6961BE5607E09B6B
04-09 10:14:41ERROR[ore.downloaders.blackhole] No nzb/torrent available: magnet:?xt=urn:btih:BFF9E2F76C55DA6CFEC07ACD6961BE5607E09B6B&dn=fifty+shades+of+grey+2015+uncut+hc+hdrip+x264+ac3+titan&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337
04-09 10:14:41INFO[tato.core.plugins.release] Tried to download, but the "torrent" downloader gave an error
```

**Comment by tomkat83** [comment]
+1, same problem here

**Comment by RuudBurger** [comment]
Use a downloader that supports magnet links, blackhole tries to download .torrent that aren't from the site.

**Comment by Grimjack69** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Thanks for answer.

I use black hole and manual move since I have my downloader in a,
sometimes, other network.

What has changed? It worked all perfect earlier?

Discussed the subject further here:
https://couchpota.to/forum/viewtopic.php?f=5&t=5619&p=27030#p27030

/TC

Ruud Burger skrev den 2015-04-22 15:56:
> Use a downloader that supports magnet links, blackhole tries to
> download .torrent that aren't from the site.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/RuudBurger/CouchPotatoServer/issues/4829#issuecomm
ent-95187069>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.17 (MingW32)

iQEcBAEBAgAGBQJVN7CBAAoJENAQwXN+2+TLpO4H/04VVd+WgFWey/bH9185Hokt
jxDpUJVAkpQ1WteQjOkP3zBUe8jyy/Sc6xNgEu4Uq/e3HMkeEgdG0NLWnVXpj3h4
bMv40+w06dbrm81farMNNwMZaGuLSz7n82JNomdtgKlKHj6HKIkVjmlnFpe4ds6n
pMoB6oo7G0jT61aMSB8nLE/1VAz5wt6DJD3uHaRgOuDC8MCLImTXVPWoWm+x8sxT
ufiG7/DntE01euONyv6lrqTLe/L1UN4Jq+ubjen0JiI/l8smsn/LJUAs3zNumEGz
a8DCEETV/hko5vjedRrMchsiGOMuOTQIdWJEmHzixtn8dIhlAf4UuLsegxxANfc=
=4an7
-----END PGP SIGNATURE-----
