### ISSUE TITLE
Issues loging in into couchpotato

### ISSUE THREAD

**Issue by Busybfr** [RuudBurger/CouchPotatoServer#4888]
Hi,
Hi

I'm trying to connect to Couchpotato through Chrome but it is not working at all... And I can find any option to reset my password... It used to work on my previous Mac but not anymore...

Could you help me please ?

Regards

Clément

**Comment by RuudBurger** [comment]
You can shutdown CP and remove the password in the settings.conf. After that, update and set the password again, making sure you have the correct one.
