### ISSUE TITLE
Release name with HDRip and 720p will never be grabbed

### ISSUE THREAD

**Issue by clement-escolano** [RuudBurger/CouchPotatoServer#4907]
### Steps to reproduce: 
1. Have a torrent with the release name having 720p and HDRip 
2. Ask couchpotato to look for this movie, with 720p and brrip 

### Information: 
Movie s  I have this with: La Famille Bélier 
Quality of the movie being searched: 720p and brrip 
Providers I use: t411 (custom one but the error is generic) 
Version of CouchPotato: git: RuudBurger:CouchPotatoServer master  edac023e  2015-04-20 23:42:31  
Running on: debian 7 

### Logs:     
05-01 10:54:14 INFO  core.media.movie.searcher  Wrong: La fam 2014 .ille Belier.HDrip.720p.X264.AC3.mkv, looking for 720p, found   brrip      

The problem : it says that this release is brrip as there is 'HDRip' in it. So it will not be grabbed with 720p search. Fine, though, when searching brrip releases, it only looks for the movie name plus brrip, missing this release.
Then this release will never be grabbed :-(

**Comment by maxcore** [comment]
Wrong fork ....

**Comment by clement-escolano** [comment]
What do you mean wrong fork?

Wrong fork for my t411 plugin? Or for couchpotato?

**Comment by maxcore** [comment]
@clement-escolano  i see after you use the plug in and not the sarakha github sorry ;)

**Comment by maxcore** [comment]
@clement-escolano you try this one https://github.com/djoole/couchpotato.provider.t411 ?

**Comment by clement-escolano** [comment]
I tried this one, but it still not working.
Though, I don't think it's related to this provider as the release name is handled by couchpotato, not by the custom plugin.

It's strange because the other providers (I tried it on kickass, seems not to have this problem).

I will compare the providers plugin to see what's different.

**Comment by clement-escolano** [comment]
I found why and a workaround :
The difference with the other providers is that other providers' search terms is the media, and then the results are parsed to define a quality for each result, then only the corresponding results are forwarded. t411 custom plugin is adding the quality to the search term and prevent 'accepted' terms (such as hdrip) to be found when searching for a specific quality (such as brrip).

My workaround was to search for all the acceptable terms instead of just the quality identifier. (For exemple, the previous search was "Famille bélier brrip" and now is "Famille bélier brrip|bdrip|hdrip|(br&rip)|hdtv" which is returning all the results we want).
You can see it on my repo if you want ;-)

**Comment by maxcore** [comment]
nice work  @clement-escolano  thx ;)
