### ISSUE TITLE
Can't handle movie names with special characters

### ISSUE THREAD

**Issue by olipayne** [RuudBurger/CouchPotatoServer#5106]
07-03 12:25:50ERROR[tato.core.plugins.renamer] Couldn't move file "/mnt/media/Downloads/complete/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.cp(tt0087544)/Nausicaa.of.the.Valley.of.the.Wind.1984.720p.BluRay.x264-CtrlHD.mkv" to "/mnt/media/Movies/Nausicaä of the Valley of the Wind (1984)/Nausicaä of the Valley of the Wind.mkv": Traceback (most recent call last):
  File "/home/oliver/.couchpotato/couchpotato/core/plugins/renamer.py", line 824, in moveFile
    shutil.move(old, dest)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/mnt/media/Movies/Nausica\xc3\xa4 of the Valley of the Wind (1984)/Nausica\xc3\xa4 of the Valley of the Wind.mkv'

**Comment by olipayne** [comment]
Ubuntu 15.04, pretty vanilla

**Comment by olipayne** [comment]
Hey Ruud, any feedback for this?

**Comment by RuudBurger** [comment]
Sorry, needed to mark it properly. This is already reported.
