### ISSUE TITLE
CP Not finding all releases of movies e.g. Spy 2015

### ISSUE THREAD

**Issue by thecrater** [RuudBurger/CouchPotatoServer#5112]
Hi. I'm not sure if I'm doing anything wrong but I've basically added all the available options to "Any quality" and yet when Couchpotato searches for Spy it seems to look here
https://thepiratebay.mn/search/"Spy+2015"/0/7/202

This is specifically the Movies DVDR category. I've actually enabled ALL qualities. Below is the actual log. It does find some releases but not all. Recently, an EVO HDRip release was released but it's never picked up.

### Steps to reproduce:
1. Add "Spy 2015" as a movie to download
2. Specify any quality in Quality criteria.

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 12:06:41)
Running on: ...

### Logs:
```
07-06 01:57:05  INFO [ie.providers.info.omdbapi] Found: Spy (2015) 
07-06 01:57:05  INFO [core.media.movie.searcher] Search for Spy in 720p ignoring ETA 
07-06 01:57:06  INFO [core.media.movie.searcher] Search for Spy in 1080p ignoring ETA 
07-06 01:57:07  INFO [core.media.movie.searcher] Search for Spy in BR-Rip ignoring ETA 
07-06 01:57:07  INFO [hpotato.core.plugins.base] Opening url: get https://thepiratebay.mn/search/%22Spy+2015%22/0/7/201,207, data: [] 
07-06 01:57:08  INFO [ie.providers.info.omdbapi] Found: Spy (2015) 
07-06 01:57:08  INFO [core.media.movie.searcher] Search for Spy in 720p ignoring ETA 
07-06 01:57:09  INFO [core.media.movie.searcher] Search for Spy in 1080p ignoring ETA 
07-06 01:57:10  INFO [edia._base.providers.base] Found: score(3072) on ThePirateBay: SPY.2015.HQCAM.REPACK.XVID.AC3.MRG 
07-06 01:57:11  INFO [edia._base.providers.base] Found: score(1705) on ThePirateBay: Spy 2015 Movies HDRip XviD AAC New Source with Sample ~ ☻rDX☻ 
07-06 01:57:11  INFO [core.media.movie.searcher] Search for Spy in DVD-R ignoring ETA 
07-06 01:57:11  INFO [hpotato.core.plugins.base] Opening url: get https://torrentz.eu/feed_verified?q=%22spy+2015%22%20size%203000m%20-%2010000m%20seed%20%3E%200, data: []

**Comment by Thijzer** [comment]
The problem I think without knowing the code is that the Hdrip format (as what would be the correct and only  format you can find your example in atm)  is not really available as a quality selection  in cp. Only the lower R5 or screener are selectable choices. 
The #hdrip is very similar to the #R6 and #webrips out their.

**Comment by RuudBurger** [comment]
hdrip falls under the "BR-Rip" quality.
