### ISSUE TITLE
error "SSL23_GET_SERVER_HELLO" prevents searching for some movies

### ISSUE THREAD

**Issue by sbisschops** [RuudBurger/CouchPotatoServer#5128]
### Steps to reproduce:
1. Do a search for "The Double", "Inside Out", "Ïnsurgent" and several other movies. Some other movies appear to be fine, but for these movies I get an error. In the case of "The Double" it's been on my Wanted list for months and even though it was released a year ago I still don't have it. Other movies either never have this problem (which is weird, as they should be using the same search mechanism), or fix themselves after a while.

Opening the link (from the log) in my browser returns a correct result, which seems to indicate there's something wrong with my SSL library. Unfortunately, I cannot update it and I don't think it should be doing searches through SSL anyway (hence the HTTP call instead of HTTPS).

### Information:
Movie(s) I have this with: "The Double", "Inside Out", "Insurgent", +others.
Quality of the movie being searched: HD (1080p/720p)
Providers I use: BitTorrent / ThePirateBay
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 14:06:41)
Running on: Synology NAS (running Synology Station Manager 4, which is old).

### Logs:
```
07-10 15:04:30 ERROR [hpotato.core.plugins.base] Failed opening url in ThePirateBay: http://pirateproxy.in/search/%22The+Double+2014%22/0/7/207 Traceback (most recent call last):
SSLError: [Errno 1] _ssl.c:507: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error 
```

**Comment by RuudBurger** [comment]
This is fixed in develop
