### ISSUE TITLE
Log shows Error in event "automation.get_movies"

### ISSUE THREAD

**Issue by jpborjas** [RuudBurger/CouchPotatoServer#5444]
As the system starts, I'm getting this error. I'm too new in CPS to know if this is affecting anything. Could you tell me if this should be a cause of concern? I looked it up but couldn't find anything:

09-13 19:33:21 INFO [       couchpotato.runner] Starting server on port 8082
09-13 19:33:21 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/configuration?api_key=xxx
09-13 19:33:21 INFO [tato.core._base.scheduler] Scheduling "movie.searcher.all", cron: day = *, hour = *, minute = 22
09-13 19:33:21 INFO [tato.core._base.scheduler] Scheduling automation.add_movies, interval: hours = 12, minutes = 0, seconds = 0
09-13 19:33:21 INFO [tato.core._base.scheduler] Scheduling updater.check, interval: hours = 6, minutes = 0, seconds = 0
09-13 19:33:21 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched, interval: hours = 0, minutes = 5, seconds = 0
09-13 19:33:21 INFO [tato.core._base.scheduler] Scheduling renamer.check_snatched_forced, interval: hours = 2, minutes = 0, seconds = 0
09-13 19:33:21 INFO [otato.core.plugins.manage] Updating manage library: /Users/jpborjas/PLEX Media/Español
09-13 19:33:21 INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/messages/?last_check=1384713000, data: []
09-13 19:33:21 INFO [hpotato.core.plugins.base] Opening url: get http://www.flixster.com/api/users/jpborjas@bellsouth.net/movies/ratings?scoreTypes=wts, data: []
09-13 19:33:21 INFO [hpotato.core.plugins.base] Opening url: get http://192.168.11.3:8080/api?output=json&apikey=xxx&mode=queue, data: []
09-13 19:33:21 INFO [potato.core._base.updater] === VERSION desktop: 3.0.1, using DesktopUpdater ===
09-13 19:33:22 ERROR [   couchpotato.core.event] Error in event "automation.get_movies", that wasn't caught: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/event.py", line 15, in runHandler
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/movie/providers/automation/base.py", line 37, in _getMovies
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/movie/providers/automation/flixster.py", line 25, in getIMDBids
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/movie/providers/automation/flixster.py", line 48, in getWatchlist
TypeError: string indices must be integers
encoding=UTF-8 debug=False args=['--quiet'] app_dir=/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7 data_dir=/Users/jpborjas/Library/Application Support/CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x10725d6a0> > options=Namespace(config_file='/Users/jpborjas/Library/Application Support/CouchPotato/settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='/Users/jpborjas/Library/Application Support/CouchPotato/couchpotato.pid', quiet=True) 
09-13 19:33:22 INFO [hpotato.core.plugins.base] Opening url: get http://192.168.11.3:8080/api?output=json&apikey=xxx&limit=15&mode=history, data: []
09-13 19:33:23 INFO [otato.core.plugins.manage] Updating manage library: /Users/jpborjas/PLEX Media/Kids
09-13 19:33:24 INFO [otato.core.plugins.manage] Updating manage library: /Users/jpborjas/PLEX Media/Movies
09-13 19:33:30 INFO [otato.core.plugins.manage] Updating manage library: /Users/jpborjas/PLEX Media/Shorts

**Comment by RuudBurger** [comment]
Your flixster user id isn't correct it seems.

**Comment by jpborjas** [comment]
It is correct. I just went to Flixster and logged out, and logged back in. I'm just entering my email address, which is my ID, right? there are no fields for password. Does this need to be a public account or something? Maybe I'm missing something else. 

Thanks.

**Comment by RuudBurger** [comment]
Try this https://couchpota.to/forum/viewtopic.php?t=2888

**Comment by jpborjas** [comment]
That worked, thanks!

On Tue, Sep 15, 2015 at 1:51 PM, Ruud Burger <notifications@github.com>
wrote:

> Try this https://couchpota.to/forum/viewtopic.php?t=2888
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RuudBurger/CouchPotatoServer/issues/5444#issuecomment-140480639>
> .
>



-- 
Thanks,

Pablo Borjas
