### ISSUE TITLE
Error properly handling accented characters.

### ISSUE THREAD

**Issue by DontTurnAround** [RuudBurger/CouchPotatoServer#5452]
### Steps to reproduce:
1. Have a copy of Les Misérables.
2. Try to import Les Misérables into Couch Potato.
3. The rename will fail because it uses "Les MisĂŠrables" instead of "Les Misérables".

As of now, I can't import Les Mis into Couch Potato. I have tried renaming it without the accent.

### Information:
Movie(s) I have this with: Les Misérables (and probably any other movie with an é in it)
Quality of the movie being searched: Doesn't matter
Providers I use: Not important.
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 63560efe (2015-08-31 16:26:55)
Running on: Synology NAS

### Logs:
```
09-14 17:11:50  INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/82695?api_key=xxx&append_to_response=alternative_titles, data: [] 
09-14 17:11:50  INFO [providers.info.themoviedb] Found: [u'Les Mis\xe9rables (2012)'] 
09-14 17:11:50  INFO [hpotato.core.plugins.base] Opening url: get http://www.omdbapi.com/?type=movie&i=tt1707386, data: [] 
09-14 17:11:50  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/info/tt1707386/, data: [] 
09-14 17:11:50  INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/movie/tt1707386?api_key=xxx&append_to_response=alternative_titles, data: [] 
09-14 17:11:51  INFO [ie.providers.info.omdbapi] Found: Les MisĂŠrables (2012) 
09-14 17:11:53  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/ismovie/tt1707386/?adding=1, data: [] 
09-14 17:11:54  INFO [ie.providers.info.omdbapi] Found: Les MisĂŠrables (2012) 
09-14 17:11:55  INFO [ie.providers.info.omdbapi] Found: Les MisĂŠrables (2012) 
```

**Comment by svallory** [comment]
It also breaks the renamer.

`A História da Eternidade...` 
becames...
`The provided media folder /Volumes/Stuff/Incoming/Movies/A Histŕ¸Łŕ¸ria da Eternidade.2014.Brazil.Naciona.HDRip.720p-Makalakato does not exist and its files could also not be found in the 'from' folder.`

I checked. The folder is there.

**Comment by svallory** [comment]
I was about to reopen this issue but just noticed the 'Already Reported' label. It would be good to link the other issue every time an issue is closed as duplicate
