### ISSUE TITLE
CP will only sync with Trakt watchlist upon restart

### ISSUE THREAD

**Issue by typistX** [RuudBurger/CouchPotatoServer#5490]
CP will only add movies from my Trakt watchlist if I restart CP.

Things I've tried: re-authenticating multiple times. Revoking access, re-granting access on Trakt. Shutting down CP, repeating authentication afterwards.

When I search the logs, the only time the words "Trakt" appeared is the time listed below in the logs. Interesting because this machine is on 24/7 and the last time Trakt appears in the logs is more than 24 hours ago.

The error right below this timestamp is attached only because it came so soon after the Trakt instance in the logs. I don't know if it has anything to do with it. 

### Steps to reproduce:
1. Add a movie to Trakt watchlist

### Information:
Movie(s) I have this with: All
Version of CouchPotato: desktop: 3.0.1
Running on: Windows 7

### Logs:
```
09-22 23:53:12  INFO [hpotato.core.plugins.base] Opening url: get https://api-v2launch.trakt.tv/sync/watchlist/movies/, data: [] 
09-22 23:53:33 ERROR [potato.core._base.updater] Failed updating desktop: Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Roaming\CouchPotato\application\appdata\CouchPotato-3.0.1.win32\couchpotato\core\_base\updater\main.py", line 455, in check
  File "esky\__init__.pyc", line 787, in find_update
  File "esky\finder.pyc", line 186, in find_versions
  File "esky\finder.pyc", line 165, in open_url
  File "urllib2.pyc", line 127, in urlopen
  File "urllib2.pyc", line 404, in open
  File "urllib2.pyc", line 422, in _open
  File "urllib2.pyc", line 382, in _call_chain
  File "urllib2.pyc", line 1222, in https_open
  File "urllib2.pyc", line 1184, in do_open
URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
 
```

**Comment by peerster** [comment]
Works for me. Running:
```
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 63560efe (2015-08-31 22:26:55)
```

**Comment by RuudBurger** [comment]
Is there a firewall or virusscanner blocking the connections? I can't do much about a timeout urlerror.
