### ISSUE TITLE
Deformed folder after post-processing

### ISSUE THREAD

**Issue by Fire69** [RuudBurger/CouchPotatoServer#5509]
### Steps to reproduce:
1. Add movie She's funny that way (tt1767372)
2. During post-processing, movie is moved but folder name is deformed => Windows shows correctly, but in WinSCP it's shown as Sheâ€™s Funny That Way ( 720p Blu-ray H264 DTS 2015).  Also, no fan-art is created and release-group is dropped.

### Information:
Movie(s) I have this with: She's funny that way (tt1767372)
Quality of the movie being searched: HD(720/1080)
Providers I use: Several nzb-indexers, not relevant for the problem I guess, movie is correctly downloaded.
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer develop) fc511e3f (2015-09-22 12:17:13)
Running on: Ubuntu Server 14.04LTS

### Logs:
```
09-26 10:47:50  INFO [tato.core.plugins.renamer] Moving "/mnt/datadisk/data/Downloads/Movies/She's Funny That Way (USURY 720p Blu-ray H264 DTS 2015).cp(tt1767372)/She's Funny That Way.mkv" to "/mnt/datadisk/data/Videos/Movies/She’s Funny That Way ( 720p Blu-ray H264 DTS 2015)/She’s Funny That Way.mkv" 
```

**Comment by RuudBurger** [comment]
Seems like it uses 2 different character for the single-quote
