### ISSUE TITLE
Issues with the ubuntu init script

### ISSUE THREAD

**Issue by TheDoctorsLife** [RuudBurger/CouchPotatoServer#5592]
Before I explain the issue I'd like to state that I can start and use couch potato just fine without  the boot init script.

Following the instructions in the README, when I get to the  point where I start the couch  potato service, I get this error.
```
systemctl status couchpotato.service
● couchpotato.service - LSB: starts instance of CouchPotato
   Loaded: loaded (/etc/init.d/couchpotato)
   Active: failed (Result: exit-code) since Thu 2015-10-15 21:01:30 EDT; 19s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16740 ExecStart=/etc/init.d/couchpotato start (code=exited, status=1/FAILURE)

Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: from couchpotato.environment import Env
Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: File "couchpotato/__init__.py", line 5, in <module>
Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: from couchpotato.api import api_docs, api_docs_missing, api
Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: File "couchpotato/api.py", line 10, in <module>
Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: from tornado.ioloop import IOLoop
Oct 15 21:01:30 benjamin-desktop couchpotato[16740]: ImportError: No module named tornado.ioloop
Oct 15 21:01:30 benjamin-desktop systemd[1]: couchpotato.service: control process exited, code=exited status=1
Oct 15 21:01:30 benjamin-desktop systemd[1]: Failed to start LSB: starts instance of CouchPotato.
Oct 15 21:01:30 benjamin-desktop systemd[1]: Unit couchpotato.service entered failed state.
Oct 15 21:01:30 benjamin-desktop systemd[1]: couchpotato.service failed.
```

**Comment by peerster** [comment]
My guess is that you use Ubuntu 15.04 (because of systemd).
The Readme for Ubuntu/debian refers to to init script for upstart.
Which init-script did you copy?

**Comment by TheDoctorsLife** [comment]
I did follow the directions from the readme, the instructions on the site are outdated (because it has you editing the actual init file instead of coping and editing the default file.

**Comment by peerster** [comment]
I don't know what instructions you're using, but the ones in README don't
say you should edit the CP init file as far as I can see.

mån 19 okt. 2015 kl 16:06 skrev Benjamin Hoffmeyer <notifications@github.com

**Comment by TheDoctorsLife** [comment]
"(Ubuntu / Debian) To run on boot copy the init script sudo cp CouchPotatoServer/init/ubuntu /etc/init.d/couchpotato"
