### ISSUE TITLE
The renamer creates a folder with a "â" in it and then tries to access the same folder using a Unicode-8 EN DASH

### ISSUE THREAD

**Issue by SamMurphy** [RuudBurger/CouchPotatoServer#5642]
The renamer creates a folder with a "â" in it and then tries to access the same folder using a Unicode-8 EN DASH

### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) e6fa8b8b (2015-10-04 10:13:08)
Running on: ...

### Logs:
```
10-29 16:45:04 ERROR [tato.core.plugins.renamer] Couldn't move file "/media/download/Mission Impossible-Rogue Nation (2015)720p V2 HQ AC3 DD2.0-rarbg eng nl subs 2LT/Movie/dut srt/Mission.Impossible.Rogue.Nation.2015.V2.720p.WEBRip.XviD.MP3-RARBG.srt" to "/media/movies/Mission Impossible â Rogue Nation (2015)/Mission Impossible â Rogue Nation.srt": Traceback (most recent call last):
  File "/usr/pbi/couchpotato-amd64/share/couchpotato/CouchPotatoServer/couchpotato/core/plugins/renamer.py", line 847, in moveFile
    shutil.copy(old, dest)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/pbi/couchpotato-amd64/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/media/movies/Mission Impossible \xe2\x80\x93 Rogue Nation (2015)/Mission Impossible \xe2\x80\x93 Rogue Nation.srt'
 
```

**Comment by Rouzax** [comment]
When changing the movie name from Couchpotato it will process correctly.
![image](https://cloud.githubusercontent.com/assets/4103090/10876844/d17e1a9c-8140-11e5-8685-2e6254ce0ba5.png)
see https://github.com/RuudBurger/CouchPotatoServer/issues/5648
