### ISSUE TITLE
Constant 403 status code for  imdb posters 

### ISSUE THREAD

**Issue by alexandrezia** [RuudBurger/CouchPotatoServer#5695]
I'm having constant 403 status when CP tries to download posters from IMDB, however, if I open ths links in a new tab, they open normaly.

![screen shot 2015-11-11 at 16 27 46](https://cloud.githubusercontent.com/assets/1100327/11099242/5a76885a-8891-11e5-9def-515c770e62d8.png)

**Comment by alexandrezia** [comment]
Why cole? This is still happening..
It's not fixed.

**Comment by RuudBurger** [comment]
Can't reproduce this
