### ISSUE TITLE
[SceneTime error] TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by davidakachaos** [RuudBurger/CouchPotatoServer#5888]
### Steps to reproduce:
1. Setup SceneTime as a search provider
2. Add a movie to search for

### Information:
Movie(s) I have this with: Deathgasm and others
Quality of the movie being searched: 720p 1080p
Providers I use: SceneTime,and others, only SceneTime gives a error
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) de141aae (2015-11-17 22:32:28)
Running on: 4.2.0-22-generic #27-Ubuntu SMP Thu Dec 17 22:57:22 UTC 2015 i686 i686 i686 GNU/Linux 

### Logs:
```
01-06 10:56:13 ERROR [oviders.torrent.scenetime] Failed to parsing SceneTime: Traceback (most recent call last):
  File "/home/david/Broncode/CouchPotatoServer/couchpotato/core/media/_base/providers/torrent/scenetime.py", line 54, in _searchOnTitle
    torrent_id = link['href'].replace('download.php/','').split('/')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
 
```

**Comment by jccroft1** [comment]
I'm still having this issue, may I ask why was it closed?
