### ISSUE TITLE
failing to snatch with sabnzbd

### ISSUE THREAD

**Issue by pahrohfit** [RuudBurger/CouchPotatoServer#5929]
### Steps to reproduce:
1. ..
2. ..

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) de141aae (2015-11-17 16:32:28)
Running on: ...

### Logs:
```
01-13 21:04:32 ERROR [.core.downloaders.sabnzbd] Error getting data from SABNZBd: {u'status': False, u'nzo_ids': '[]'} 
```

**Comment by sievo** [comment]
I had the same error till I updated Sabnzbdplus from 0.8.0beta4 to beta 5.
