### ISSUE TITLE
Unable to login into CouchPotato after it auto-updated to latest version on branch: Master

### ISSUE THREAD

**Issue by BladesKnight** [RuudBurger/CouchPotatoServer#5997]
Platform: Synology DSM 5.2-5644 Update 3

Accessing the webpage results in the Login prompt but the account that I usually use (Admin) doesn’t work and it just throws me back to the login page.

Pls help. Thanks.

**Comment by bernhardmostrey** [comment]
having the same problem in all browsers, RuudBurger, please fix!
