### ISSUE TITLE
WDTV Metadata

### ISSUE THREAD

**Issue by gootard** [RuudBurger/CouchPotatoServer#700]
Hi great program but the current couch potato server v2 only seems to have Metadata support under Renamer for XBMC. Is there any way to add WDTV support with .xml files. it also gets .backdrop folder but i think WDTV does that on it's own. thanks!

**Comment by keep3r** [comment]
Please assign this issue to me. I created the necessary script for WDTV metadata:

![image](https://cloud.githubusercontent.com/assets/688376/8160379/756d207a-136f-11e5-809f-727d3381de88.png)

**Comment by RuudBurger** [comment]
Please send a Pull Request so I can review

**Comment by RuudBurger** [comment]
#5058
